# Generated by Django 5.2.5 on 2025-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FOLLOWERS', 'Followers Only')], default='PUBLIC', max_length=10),
        ),
    ]
