# Generated by Django 5.2.5 on 2025-09-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_post_status_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
