# Generated by Django 5.2.5 on 2025-08-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_post_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='privacy',
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='profile_pictures/default.png', upload_to='post_images/'),
            preserve_default=False,
        ),
    ]
