# Generated by Django 5.2.5 on 2025-09-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='is_Admin',
            new_name='is_admin',
        ),
    ]
