# Generated by Django 5.2.5 on 2025-10-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_main',
            field=models.CharField(default='rgba(255,255,255,0.8)', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='bg_sidebar',
            field=models.CharField(default='rgba(255,179,217,0.6)', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='color_accent',
            field=models.CharField(default='#ff4da6', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='color_accent_dark',
            field=models.CharField(default='#ff80bf', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='color_accent_light',
            field=models.CharField(default='#ffb3d9', max_length=7),
        ),
    ]
