# Generated by Django 5.2.5 on 2025-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_bg_main_profile_bg_sidebar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(default='default/banner.jpg', upload_to='profile_banner'),
        ),
    ]
