# Generated by Django 5.2.5 on 2025-10-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_profile_profile_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(default='default/banner.jpg', upload_to='profile_pics'),
        ),
    ]
