# Generated by Django 5.2.5 on 2025-10-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_profile_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_song',
            field=models.FileField(blank=True, null=True, upload_to='profile_song/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(default='default/banner.jpg', upload_to='profile_banners'),
        ),
    ]
